// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4model0_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model3_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model7_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model8_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mvn_covariance_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mvn_precision_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4model0_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model0_mod, 0},
    {"_rcpp_module_boot_stan_fit4model1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model1_mod, 0},
    {"_rcpp_module_boot_stan_fit4model2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model2_mod, 0},
    {"_rcpp_module_boot_stan_fit4model3_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model3_mod, 0},
    {"_rcpp_module_boot_stan_fit4model7_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model7_mod, 0},
    {"_rcpp_module_boot_stan_fit4model8_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model8_mod, 0},
    {"_rcpp_module_boot_stan_fit4mvn_covariance_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mvn_covariance_mod, 0},
    {"_rcpp_module_boot_stan_fit4mvn_precision_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mvn_precision_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsae(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
