// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4besag_morris_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bym2_centroid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bym2_covariance_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bym2_integrated_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bym2_morris_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4bym2_precision_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4centroid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4constant_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4iid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4integrated_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mvn_covariance_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4mvn_precision_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4besag_morris_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4besag_morris_mod, 0},
    {"_rcpp_module_boot_stan_fit4bym2_centroid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bym2_centroid_mod, 0},
    {"_rcpp_module_boot_stan_fit4bym2_covariance_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bym2_covariance_mod, 0},
    {"_rcpp_module_boot_stan_fit4bym2_integrated_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bym2_integrated_mod, 0},
    {"_rcpp_module_boot_stan_fit4bym2_morris_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bym2_morris_mod, 0},
    {"_rcpp_module_boot_stan_fit4bym2_precision_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bym2_precision_mod, 0},
    {"_rcpp_module_boot_stan_fit4centroid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4centroid_mod, 0},
    {"_rcpp_module_boot_stan_fit4constant_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4constant_mod, 0},
    {"_rcpp_module_boot_stan_fit4iid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4iid_mod, 0},
    {"_rcpp_module_boot_stan_fit4integrated_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4integrated_mod, 0},
    {"_rcpp_module_boot_stan_fit4mvn_covariance_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mvn_covariance_mod, 0},
    {"_rcpp_module_boot_stan_fit4mvn_precision_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4mvn_precision_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsae(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
